apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
  {{- include "chart.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    any: true
  endpoints:
    - interval: 30s
      port: notify-master
      path: /actuator/prometheus
      scheme: https
      tlsConfig:
        insecureSkipVerify: true

