apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: notify-master
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 8082
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
