version: '3.5'
services:
  rmq:
    image: rabbitmq:3.8-management
    container_name: rmq
    environment:
      - RABBITMQ_SSL_CERTFILE=/certs/rmq.crt
      - RABBITMQ_SSL_KEYFILE=/certs/rmq.key
      - RABBITMQ_SSL_CACERTFILE=/certs/rootCA.crt
      - RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT=false
    volumes:
      - /c/java/docker-shared/rmq:/certs
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
    logging:
      driver: json-file
  mongo:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - /c/java/docker-shared/mongo:/etc/ssl/
    command: --tlsMode allowTLS --tlsCertificateKeyFile /etc/ssl/mongo.pem --tlsCAFile /etc/ssl/rootCA.pem --tlsAllowConnectionsWithoutCertificates
    ports:
      - '27017-27019:27017-27019'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      #start_period: 2s
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - 888:8081
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_BASICAUTH_USERNAME=dev
      - ME_CONFIG_BASICAUTH_PASSWORD=dev
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_SSLVALIDATE=false
      - ME_CONFIG_MONGODB_SSL=true
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_CA_FILE=/etc/ssl/mongo.pem
    volumes:
      - /c/java/docker-shared/mongo:/etc/ssl/
#    links:
#      - "mongo"
    depends_on:
      mongo:
        condition: service_healthy
  #    - "mongo"
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: es
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
  kib:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kib
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es:9200
      ELASTICSEARCH_HOSTS: http://es:9200
  prom:
    container_name: prom
    image: prometheus:local
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    links:
      - alert:alert
  alert:
    container_name: alert
    image: alertmanager:local
    ports:
      - 9093:9093
    restart: always
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
  telegram:
    container_name: telegram
    image: telegram:latest
    ports:
      - "8088:8088"
    logging:
      driver: json-file
  cytric:
    container_name: cytric
    image: cytric-sim
    ports:
      - "18080:18080"
    logging:
      driver: json-file
  extapp1:
    container_name: telephonica1
    image: extapp
    ports:
    - 8091:8091
    logging:
      driver: json-file
  extapp2:
    container_name: telephonica2
    image: extapp
    ports:
      - 8092:8091
    logging:
      driver: json-file
  extapp3:
    container_name: bosch
    image: extapp
    ports:
      - 8093:8091
    logging:
      driver: json-file
  extapp4:
    container_name: itelya
    image: extapp
    ports:
      - 8094:8091
    logging:
      driver: json-file
  extapp5:
    container_name: daimler
    image: extapp
    ports:
      - 8095:8091
    logging:
      driver: json-file
  kc:
    container_name: kc
    image: quay.io/keycloak/keycloak:15.0.0
    ports:
      - 8780:8080
      - 8443:8443
    volumes:
      - /c/java/docker-shared/keycloak:/etc/x509/https
    command: -b 0.0.0.0 -bmanagement 0.0.0.0 -Dkeycloak.profile.feature.upload_scripts=enabled
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
  jg:
    container_name: jg
    image: jaegertracing/all-in-one:1.19
    ports:
      - 5775:5775
      - 6831:6831
      - 6832:6832
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411