apiVersion: v1
kind: ServiceAccount
metadata:
  name: ccbd-service-monitor
  namespace: monitoring
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: role-ccbd-service-monitor
 namespace: monitoring
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: role-ccbd-service-binding
 namespace: monitoring
subjects:
- kind: ServiceAccount
  name: ccbd-service-monitor
  namespace: monitoring
roleRef:
 kind: Role
 name: role-ccbd-service-monitor
 apiGroup: rbac.authorization.k8s.io
