replicas: 1

image:
  repository: nexus.secure.ifao.net:8443/ifao/dip/keycloak
  tag: "@version@"

podSecurityContext:
  fsGroup: 1000600000

securityContext:
  runAsUser: 1000600000
  runAsNonRoot: true

extraEnv: |
  - name: KEYCLOAK_USER_FILE
    value: /secrets/keycloak-admin-creds/username
  - name: KEYCLOAK_PASSWORD_FILE
    value: /secrets/keycloak-admin-creds/password
  - name: DB_VENDOR
    value: h2
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"
  - name: KEYCLOAK_LOGLEVEL
    value: ERROR
  - name: ROOT_LOGLEVEL
    value: INFO
  - name: WILDFLY_LOGLEVEL
    value: INFO
  - name: JAVA_OPTS
    value: >-
      -XX:+UseContainerSupport
      -XX:MaxRAMPercentage=50.0
      -Djava.net.preferIPv4Stack=true
      -Djboss.modules.system.pkgs=$JBOSS_MODULES_SYSTEM_PKGS
      -Djava.awt.headless=true
      -Dkeycloak.profile.feature.upload_scripts=enabled
      -Dkeycloak.import=/opt/realms/realm-openapi.json,/opt/realms/realm-cytricng.json,/opt/realms/realm-openapi-latest.json
  - name: KEYCLOAK_STATISTICS
    value: all

resources:
  limits:
    cpu: "600m"
    memory: "3Gi"
  requests:
    cpu: "200m"
    memory: "1Gi"

route:
  enabled: true

extraVolumes: |
  - name: keycloak-certificate
    secret:
      defaultMode: 420
      secretName: keycloak-cert
  - name: keycloak-admin-creds
    secret:
      secretName: keycloak-admin-creds

extraVolumeMounts: |
  - mountPath: /etc/x509/https
    name: keycloak-certificate
    readOnly: true
  - name: keycloak-admin-creds
    mountPath: /secrets/keycloak-admin-creds
    readOnly: true

livenessProbe: |
  httpGet:
    path: /auth/
    port: http
  initialDelaySeconds: 500
  timeoutSeconds: 5
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3

readinessProbe: |
  httpGet:
    path: /auth/realms/master
    port: http
  initialDelaySeconds: 300
  timeoutSeconds: 1
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 6

postgresql:
  enabled: false

serviceMonitor:
  enabled: true
