#!/bin/sh
#
# An example hook script to check the commit log message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.
#
# To enable this hook, rename this file to "commit-msg".

# Uncomment the below to add a Signed-off-by line to the message.
# Doing this in a hook is a bad idea in general, but the prepare-commit-msg
# hook is more suited to it.
#
# SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
# grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"

# Prevent commit with an empty commit message

empty_lines=`grep -E "^[[:space:]]*$" $1 | wc -l`
comment_lines=`grep -E "^[[:space:]]*#" $1 | wc -l`
total_lines=`cat $1 | wc -l`

if test $((empty_lines + comment_lines)) = $total_lines; then
   echo "[POLICY] Empty commit message - commit aborted."
   exit 1
fi
