#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
    # Note that the use of brackets around a tr range is ok here, (it's
    # even required, for portability to Solaris 10's /usr/bin/tr), since
    # the square bracket bytes happen to fall in the designated range.
    test $(git diff --cached --name-only --diff-filter=A -z $against |
      LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
    cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
  exit 1
fi

# Check for non-ASCII characters
#
# Match A(dded), M(odified), R(enamed) and C(opied) files.

# Output style escapes
ERROR="\033[0;31m"
INFO="\033[0;32m"
WARN="\033[0;33m"
BOLD="\033[1m"
NORMAL="\033[0m"

EXIT_STATUS=0
FILES=`git status --porcelain | grep -E "^[[:space:]]*[AMRC][[:space:]]+" | sed -r s/^\ *[AMRC]\ +\(.+\)/\\\1/`

# Check for non-ASCII characters, tabs or spaces
for file in $FILES; do
    if test -f $file && LANG=C grep -l --binary-files=without-match '[^[:print:][:space:]]' $file > /dev/null; then
        echo -e "${ERROR}[POLICY]: $file contains non-ASCII symbol/s - commit will be aborted.${NORMAL}"
        EXIT_STATUS=1
    elif test -f $file && LANG=C grep -l --binary-files=without-match -P '\t' $file; then
        echo -e "${ERROR}[POLICY]: $file contains tabs, replace them with spaces and try again - commit will be aborted.${NORMAL}"
        EXIT_STATUS=1
    fi
done
if test $EXIT_STATUS -ne 0; then
    exit $EXIT_STATUS
fi

sh ./scripts/jindent.sh ./scripts/data-format/ifao-style.xjs -checksum
EXIT_STATUS=$?
if test $EXIT_STATUS -ne 0; then
    # Jindent 5.0.3 (but not 5.0.1) reports exit code 2
    # if formating completes successfully but warnings are detected,
    # but this is not a reason for commit prevention.
    if test $EXIT_STATUS -eq 2; then
        EXIT_STATUS=0
    elif test $EXIT_STATUS -eq 126; then
        echo -e "${INFO}Jindent finished successfully."
        echo -e "${WARN}BUT you need to add the formatted files to Git index first - commit will be aborted.${NORMAL}"
    else
        echo -e "${ERROR}${BOLD}[POLICY]: Jindent finished with an error - commit will be aborted.${NORMAL}"
    fi
    exit $EXIT_STATUS
fi


# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --