apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-proxy-updater
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-mongodb-proxy
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-mongodb-proxy-binding
subjects:
- kind: ServiceAccount
  name: mongodb-proxy-updater
roleRef:
  kind: Role
  name: role-mongodb-proxy
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-proxy
  labels:
    app: mongodb-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-proxy
  template:
    metadata:
      labels:
        app: mongodb-proxy
    spec:
      serviceAccountName: mongodb-proxy-updater
      imagePullSecrets:
        - name: nexus
      containers:
        - name: mongodb-proxy
          image: nexus.secure.ifao.net:9343/mongodb-proxy:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /ca-readonly
              name: ca
          resources:
            #requests:
              #  cpu: 500
              # memory: 1Gi
            limits:
              cpu: 2
              memory: 2Gi
      volumes:
      - name: ca
        secret:
          defaultMode: 256
          secretName: mongodb-replicaset-ca
