apiVersion: v1
kind: Service
metadata:
  name: mongodb-proxy
spec:
  type: NodePort
  selector:
    app: mongodb-proxy
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb-replicaset
    release: mongodb-replicaset
    statefulset.kubernetes.io/pod-name: mongodb-replicaset-0

